#
# Module manifest for module 'GoogleCloudPowerShell'
#
# Generated by: Google Inc
#
# Generated on: 9/17/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '..\PowerShell\GoogleCloud\1.0.1.10\GoogleCloud.psm1'

# Version number of this module.
ModuleVersion = '1.0.1.10'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'e74637e6-7a4e-422d-bb9c-ca50809d78bb'

# Author of this module
Author = 'Google Inc'

# Company or vendor of this module
CompanyName = 'Google Inc'

# Copyright statement for this module
Copyright = 'Google Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell cmdlets for the Google Cloud Platform.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 
               '..\PowerShell\GoogleCloud\1.0.1.10\GoogleCloudPlatform.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-GcsBucketAcl', 'Get-GcsBucketAcl', 'Remove-GcsBucketAcl', 
               'Add-GcsObjectAcl', 'Get-GcsObjectAcl', 'Remove-GcsObjectAcl', 
               'Add-GcsDefaultObjectAcl', 'Get-GcsDefaultObjectAcl', 
               'Remove-GcsDefaultObjectAcl', 'Get-GcsBucket', 'New-GcsBucket', 
               'Remove-GcsBucket', 'Test-GcsBucket', 'Remove-GcsBucketLogging', 
               'Write-GcsBucketLogging', 'Remove-GcsBucketWebsite', 
               'Write-GcsBucketWebsite', 'New-GcsObject', 'Get-GcsObject', 
               'Set-GcsObject', 'Remove-GcsObject', 'Read-GcsObject', 
               'Write-GcsObject', 'Test-GcsObject', 'Copy-GcsObject', 
               'Get-GcSqlBackupRun', 'Remove-GcSqlBackupRun', 'Get-GcSqlFlags', 
               'Get-GcSqlInstance', 'Add-GcSqlInstance', 'Remove-GcSqlInstance', 
               'Export-GcSqlInstance', 'Import-GcSqlInstance', 
               'Restart-GcSqlInstance', 'Start-GcSqlReplica', 'Stop-GcSqlReplica', 
               'ConvertTo-GcSqlInstance', 'Restore-GcSqlInstanceBackup', 
               'Update-GcSqlInstance', 'Invoke-GcSqlInstanceFailover', 
               'New-GcSqlInstanceConfig', 'New-GcSqlInstanceReplicaConfig', 
               'Get-GcSqlOperation', 'New-GcSqlSettingConfig', 'Get-GcSqlSslCert', 
               'Add-GcSqlSslCert', 'Remove-GcSqlSslCert', 'Add-GcSqlSslEphemeral', 
               'Reset-GcSqlSslConfig', 'Get-GcSqlTiers', 'Get-GcpsMessage', 
               'New-GcpsMessage', 'Publish-GcpsMessage', 'Send-GcpsAck', 
               'Set-GcpsAckDeadline', 'New-GcpsSubscription', 'Get-GcpsSubscription', 
               'Set-GcpsSubscriptionConfig', 'Remove-GcpsSubscription', 
               'New-GcpsTopic', 'Get-GcpsTopic', 'Remove-GcpsTopic', 'Get-GcLogEntry', 
               'New-GcLogMonitoredResource', 'New-GcLogEntry', 'Get-GcLog', 
               'Remove-GcLog', 'Get-GcLogMetric', 'New-GcLogMetric', 'Set-GcLogMetric', 
               'Remove-GcLogMetric', 'Get-GcLogSink', 'New-GcLogSink', 'Set-GcLogSink', 
               'Remove-GcLogSink', 'Get-GcdChange', 'Add-GcdChange', 
               'Get-GcdManagedZone', 'Add-GcdManagedZone', 'Remove-GcdManagedZone', 
               'Get-GcdQuota', 'Get-GcdResourceRecordSet', 
               'New-GcdResourceRecordSet', 'Remove-GkeNodePool', 
               'Get-GceMachineType', 'Get-GceManagedInstanceGroup', 
               'Add-GceManagedInstanceGroup', 'Remove-GceManagedInstanceGroup', 
               'Set-GceManagedInstanceGroup', 'Wait-GceManagedInstanceGroup', 
               'New-GceNetwork', 'Get-GceNetwork', 'Remove-GceNetwork', 'Add-GceRoute', 
               'Get-GceRoute', 'Remove-GceRoute', 'Add-GceSnapshot', 'Get-GceSnapshot', 
               'Remove-GceSnapshot', 'Get-GceAddress', 'Add-GceAddress', 
               'Remove-GceAddress', 'Get-GceBackendService', 
               'New-GceAttachedDiskConfig', 'Get-GceFirewall', 'Add-GceFirewall', 
               'Remove-GceFirewall', 'Set-GceFirewall', 'Get-GceForwardingRule', 
               'Add-GceHealthCheck', 'Get-GceHealthCheck', 'Remove-GceHealthCheck', 
               'Set-GceHealthCheck', 'Get-GceImage', 'Add-GceImage', 'Remove-GceImage', 
               'Disable-GceImage', 'Get-GceInstance', 'Add-GceInstance', 
               'Remove-GceInstance', 'Start-GceInstance', 'Stop-GceInstance', 
               'Restart-GceInstance', 'Set-GceInstance', 'Get-GceDisk', 'New-GceDisk', 
               'Resize-GceDisk', 'Remove-GceDisk', 'New-GceInstanceConfig', 
               'Get-GceInstanceTemplate', 'Add-GceInstanceTemplate', 
               'Remove-GceInstanceTemplate', 'Get-GceMetadata', 
               'New-GceServiceAccountConfig', 'Get-GceTargetPool', 
               'Set-GceTargetPool', 'Get-GceTargetProxy', 'Get-GceUrlMap', 
               'New-GceFirewallProtocol', 'Get-GcpProject', 'Get-GcIamPolicyBinding', 
               'Add-GcIamPolicyBinding', 'Remove-GcIamPolicyBinding'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Google', 'Cloud', 'Compute', 'Storage', 'GCS', 'GCE', 'SQL', 'DNS'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/GoogleCloudPlatform/google-cloud-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/GoogleCloudPlatform/google-cloud-powershell/master/Assets/LOGO.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'This module contains a set of cmdlets that let you manage Google Cloud Platform resources.
Currently, the supported resources are Google Cloud Storage, Google Compute Engine,
Google Cloud DNS and Google Cloud SQL.

The module also contains a PowerShell provider for Google Cloud Storage. This provider allows
you to use commands like ''cd'', ''dir'', ''copy'' and ''del'' to navigate and manipulate your data
in Cloud Storage as if the data were on a local file system.

The module requires Google Cloud SDK to work.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIUEgYJKoZIhvcNAQcCoIIUAzCCE/8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBXTdHjGxRTxWgS
# Tr/iW5iTfpAMNwmNcpwRUp3AOdh256CCDtswggSZMIIDgaADAgECAg8WiPA5JV5j
# jmkUOQfmMwswDQYJKoZIhvcNAQEFBQAwgZUxCzAJBgNVBAYTAlVTMQswCQYDVQQI
# EwJVVDEXMBUGA1UEBxMOU2FsdCBMYWtlIENpdHkxHjAcBgNVBAoTFVRoZSBVU0VS
# VFJVU1QgTmV0d29yazEhMB8GA1UECxMYaHR0cDovL3d3dy51c2VydHJ1c3QuY29t
# MR0wGwYDVQQDExRVVE4tVVNFUkZpcnN0LU9iamVjdDAeFw0xNTEyMzEwMDAwMDBa
# Fw0xOTA3MDkxODQwMzZaMIGEMQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRl
# ciBNYW5jaGVzdGVyMRAwDgYDVQQHEwdTYWxmb3JkMRowGAYDVQQKExFDT01PRE8g
# Q0EgTGltaXRlZDEqMCgGA1UEAxMhQ09NT0RPIFNIQS0xIFRpbWUgU3RhbXBpbmcg
# U2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6ek939c3CMke
# OLJSU0JtIvGxxAYEa579gnRQQ33GoLsfTvkCcSax70PYg4xI/OcPl3qa65zepqMO
# OxxEGHWOeKUXaf5JGKTiu1xO/o4qVHpQ8NX2zJHnmXnX3nmU15Yz/g6DviK/YxYs
# o90oG689q+qX0vG/BBDnPUhF/R9oZcF/WZlpwCIxDGJup1xlASGwY8QiGCfu5vzS
# AD1HLqi4hlZdBNwTFyVuHN9EDxXNt9ulV3ZCbwBogpnS48He8IuUV0zsCJAiIc4i
# K5gMQuZCk5SYk+/9Btk/vFubVDwgse5q1kd6xauA6TCa3vGkP1VNCgk0inUp0mmt
# lw9Qv/jKCQIDAQABo4H0MIHxMB8GA1UdIwQYMBaAFNrtZHQUnBQ8q92Zqb1bKE2L
# PMnYMB0GA1UdDgQWBBSOay0za/Qzp5OzE5ql4Ar3EjVqiDAOBgNVHQ8BAf8EBAMC
# BsAwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDBCBgNVHR8E
# OzA5MDegNaAzhjFodHRwOi8vY3JsLnVzZXJ0cnVzdC5jb20vVVROLVVTRVJGaXJz
# dC1PYmplY3QuY3JsMDUGCCsGAQUFBwEBBCkwJzAlBggrBgEFBQcwAYYZaHR0cDov
# L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQUFAAOCAQEAujMkQECMfNtY
# n7NgmLL1wDH+6x9uUPYK4OTmga0mh6Lf/bPa9HPzAPspG4kbFT7ba1KTK8SsOYHX
# PGdXmjk24CgImuM5T5uJCX97xWF/WYkyJQpqrho+8KInqLbDuIf3FgRIQT1c2Oyf
# TSAxBNlloe3NaQdTFj3dNgIKiOtA5QYwC7gWS9zvvFUJ/8Y+Ei52s9zOQu/5dlfh
# twoFQJhYml1xFpNxjGWB6m/ziff7c62057/Zjm+qC08l87jh1d11mGiB+KrA0YDC
# xMQ5icH2yZ5s13T52Zf4T8KaCs1ej/gZ6eCln8TwkiHmLXklySL5w/A6hFetOhb0
# Y5QQHV3QxjCCBN0wggPFoAMCAQICECqcIayqpjo8WKe5MivulI0wDQYJKoZIhvcN
# AQELBQAwfzELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFFN5bWFudGVjIENvcnBvcmF0
# aW9uMR8wHQYDVQQLExZTeW1hbnRlYyBUcnVzdCBOZXR3b3JrMTAwLgYDVQQDEydT
# eW1hbnRlYyBDbGFzcyAzIFNIQTI1NiBDb2RlIFNpZ25pbmcgQ0EwHhcNMTUxMjE2
# MDAwMDAwWhcNMTgxMjE2MjM1OTU5WjBkMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
# Q2FsaWZvcm5pYTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzETMBEGA1UECgwKR29v
# Z2xlIEluYzETMBEGA1UEAwwKR29vZ2xlIEluYzCCASIwDQYJKoZIhvcNAQEBBQAD
# ggEPADCCAQoCggEBAMQNgsRBKSjl/Qw/pccOZr2lxIuziqyEA5+ELjjfBrFO/TNg
# WDg23SLP3/FQH0fxVQXBgQHnKD7/X4kSCerfqhdJLHGrSNGdLvRR4APg9xZsewwi
# dW1+H0nEQyiIQdxs7RMqA5nrYhT5NSZuEiwD4veBuRoFZwZ8phpb7SAV5S2D3o42
# +h4IQRwaSJ+28cMvAhNLp8q67xxYb47TDxSkCytduvRaow1kNKWK149NImZNpK7h
# +c3GWObGEXcy37rfOUiK0SfXM3eoyeRe7foSz/P9+u6rgIYTNOtafm9sG+7YS7LM
# d5iHrMr1u2RvSR5bkWNQH2MtgydzB58rFvR7cSkCAwEAAaOCAW4wggFqMAkGA1Ud
# EwQCMAAwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMGYGA1Ud
# IARfMF0wWwYLYIZIAYb4RQEHFwMwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5
# bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGRoXaHR0cHM6Ly9kLnN5bWNiLmNvbS9y
# cGEwHwYDVR0jBBgwFoAUljtT8Hkzl699g+8uK8zKt4YecmYwKwYDVR0fBCQwIjAg
# oB6gHIYaaHR0cDovL3N2LnN5bWNiLmNvbS9zdi5jcmwwVwYIKwYBBQUHAQEESzBJ
# MB8GCCsGAQUFBzABhhNodHRwOi8vc3Yuc3ltY2QuY29tMCYGCCsGAQUFBzAChhpo
# dHRwOi8vc3Yuc3ltY2IuY29tL3N2LmNydDARBglghkgBhvhCAQEEBAMCBBAwFgYK
# KwYBBAGCNwIBGwQIMAYBAQABAf8wDQYJKoZIhvcNAQELBQADggEBACPnk5Ov26hN
# r69U6NgmlYDNI5Fw7QtbsenY3R5AN3iXGO2f5YRnhQZQtfGr5oNaF3tRvn8Yxkde
# K6r0oB81PgWfQ0D3n9H04acC847Jcf4YN0hC1+Q2cxCS1NjZHMQmWBhntiQiaWMC
# 90lRa3X2tH1W/yz0iPdnbwiG84sLMAJ/bZLZTr2Z93t0hgzLua0sv0R5qACCnGL0
# qhHf0r/w4ZIoEZC7XjOIhpZN3Quvw2ehlS1EMsb697iAwU44vh+2hPfxITFnSaif
# inUH3zs6w+pyzUB/p9p8yS58qQzxXVyCQmK5SZSPcOalwF8X+0A2wTqJYwMcP2ag
# PY+hTE5crL8wggVZMIIEQaADAgECAhA9eNf5dklgsmF99PAeyoYqMA0GCSqGSIb3
# DQEBCwUAMIHKMQswCQYDVQQGEwJVUzEXMBUGA1UEChMOVmVyaVNpZ24sIEluYy4x
# HzAdBgNVBAsTFlZlcmlTaWduIFRydXN0IE5ldHdvcmsxOjA4BgNVBAsTMShjKSAy
# MDA2IFZlcmlTaWduLCBJbmMuIC0gRm9yIGF1dGhvcml6ZWQgdXNlIG9ubHkxRTBD
# BgNVBAMTPFZlcmlTaWduIENsYXNzIDMgUHVibGljIFByaW1hcnkgQ2VydGlmaWNh
# dGlvbiBBdXRob3JpdHkgLSBHNTAeFw0xMzEyMTAwMDAwMDBaFw0yMzEyMDkyMzU5
# NTlaMH8xCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlv
# bjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0d29yazEwMC4GA1UEAxMnU3lt
# YW50ZWMgQ2xhc3MgMyBTSEEyNTYgQ29kZSBTaWduaW5nIENBMIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl4MeABavLLHSCMTXaJNRYB5x9uJHtNtYTSNi
# arS/WhtR96MNGHdou9g2qy8hUNqe8+dfJ04LwpfICXCTqdpcDU6kDZGgtOwUzpFy
# VC7Oo9tE6VIbP0E8ykrkqsDoOatTzCHQzM9/m+bCzFhqghXuPTbPHMWXBySO8Xu+
# MS09bty1mUKfS2GVXxxw7hd924vlYYl4x2gbrxF4GpiuxFVHU9mzMtahDkZAxZeS
# itFTp5lbhTVX0+qTYmEgCscwdyQRTWKDtrp7aIIx7mXK3/nVjbI13Iwrb2pyXGCE
# nPIMlF7AVlIASMzT+KV93i/XE+Q4qITVRrgThsIbnepaON2b2wIDAQABo4IBgzCC
# AX8wLwYIKwYBBQUHAQEEIzAhMB8GCCsGAQUFBzABhhNodHRwOi8vczIuc3ltY2Iu
# Y29tMBIGA1UdEwEB/wQIMAYBAf8CAQAwbAYDVR0gBGUwYzBhBgtghkgBhvhFAQcX
# AzBSMCYGCCsGAQUFBwIBFhpodHRwOi8vd3d3LnN5bWF1dGguY29tL2NwczAoBggr
# BgEFBQcCAjAcGhpodHRwOi8vd3d3LnN5bWF1dGguY29tL3JwYTAwBgNVHR8EKTAn
# MCWgI6Ahhh9odHRwOi8vczEuc3ltY2IuY29tL3BjYTMtZzUuY3JsMB0GA1UdJQQW
# MBQGCCsGAQUFBwMCBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCAQYwKQYDVR0RBCIw
# IKQeMBwxGjAYBgNVBAMTEVN5bWFudGVjUEtJLTEtNTY3MB0GA1UdDgQWBBSWO1Pw
# eTOXr32D7y4rzMq3hh5yZjAfBgNVHSMEGDAWgBR/02Wnwt3su/AwCfNDOfoCrzMx
# MzANBgkqhkiG9w0BAQsFAAOCAQEAE4UaHmmpN/egvaSvfh1hU/6djF4MpnUeeBcj
# 3f3sGgNVOftxlcdlWqeOMNJEWmHbcG/aIQXCLnO6SfHRk/5dyc1eA+CJnj90Htf3
# OIup1s+7NS8zWKiSVtHITTuC5nmEFvwosLFH8x2iPu6H2aZ/pFalP62ELinefLyo
# qqM9BAHqupOiDlAiKRdMh+Q6EV/WpCWJmwVrL7TJAUwnewusGQUioGAVP9rJ+01M
# j/tyZ3f9J5THujUOiEn+jf0or0oSvQ2zlwXeRAwV+jYrA9zBUAHxoRFdFOXivSdL
# VL4rhF4PpsN0BQrvl8OJIrEfd/O9zUPU8UypP7WLhK9k8tAUITGCBI0wggSJAgEB
# MIGTMH8xCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlv
# bjEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0d29yazEwMC4GA1UEAxMnU3lt
# YW50ZWMgQ2xhc3MgMyBTSEEyNTYgQ29kZSBTaWduaW5nIENBAhAqnCGsqqY6PFin
# uTIr7pSNMA0GCWCGSAFlAwQCAQUAoIGEMBgGCisGAQQBgjcCAQwxCjAIoAKAAKEC
# gAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIFnEKn/qyxAcO6IEL/PDz+StnpOR
# W8T1UOnllcDIA2gZMA0GCSqGSIb3DQEBAQUABIIBAG86m9D8TfapUn8HWXjHzRR3
# s2h13soAIx3an2WFDhfUE/9HWn6yC5SGxprGuwijuIA3z4rMwpXOQ0sJxzalagKz
# E7qnsL5Za18KXvcJ49n0WknrDEp1tt1DaNp41Ryp91X+jL4VvP4sQGt9+rWRgCnO
# r0R09pLx4Wdu1VG4sJ4wkx1ACz6D2X57nqk7WcxcmpNrXGI2nAzU25KsxHUHIInV
# xzevYpbm02+kpnYYFWzCSdARamsgl9duyxaI7urPq7MH2CYxCYkXa3H7vaTA6B3O
# pWqL0ZNAjNilTad5G8Di7OuCoq5bUAt9ZPRwUbc/9dUhzZaL4U14X6s8FqDs4Yeh
# ggJDMIICPwYJKoZIhvcNAQkGMYICMDCCAiwCAQEwgakwgZUxCzAJBgNVBAYTAlVT
# MQswCQYDVQQIEwJVVDEXMBUGA1UEBxMOU2FsdCBMYWtlIENpdHkxHjAcBgNVBAoT
# FVRoZSBVU0VSVFJVU1QgTmV0d29yazEhMB8GA1UECxMYaHR0cDovL3d3dy51c2Vy
# dHJ1c3QuY29tMR0wGwYDVQQDExRVVE4tVVNFUkZpcnN0LU9iamVjdAIPFojwOSVe
# Y45pFDkH5jMLMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcB
# MBwGCSqGSIb3DQEJBTEPFw0xODA5MTcyMjExMjBaMCMGCSqGSIb3DQEJBDEWBBRl
# cWj9KdFHB7aag8CHh7DVMZyWmTANBgkqhkiG9w0BAQEFAASCAQCCQ2Fc1tNIg3Qw
# OPRFTAXnFj0lwCnWqgwrlbA07WRDy1trO2zQItPfQJN+yZeXnecpN+oPWyqXuDYi
# LYcHhhRortGwdebFtR3gILjqlNA0slRRwGfvm2qP5zSIZKaTjh9DpvJ5mqPm9uS7
# oH0yaI/m8OcI6jFXiFkcluBGmdmNQ1wqGPy9OQgsqnMKr00oSc7Pu0bSJl3lj3TC
# qqABUHSRZ/iweCjKjtXkzBp6EgXGEaxetBJD2X7o7m/wSZY6DikGoghEkY8j8mFA
# DxoP7b0Y7IgUqHBD0HoK08URbe8aWxhCE2Y9K82IR9B6xy+tC1hEILytc1OP7MMp
# W/EicsaW
# SIG # End signature block
